// <auto-generated />
using System;
using System.Text.Json;
using AiMedia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiMedia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317211601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "job_status", new[] { "queued", "processing", "completed", "failed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "model_tier", new[] { "free", "standard", "premium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_type", new[] { "image_gen", "image_to_video", "text_to_video", "voice", "transcription", "background_removal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_plan", new[] { "free", "starter", "creator", "pro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", new[] { "purchase", "deduction", "refund", "bonus", "expiry", "reservation" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiMedia.Domain.Entities.CreditPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.HasKey("Id")
                        .HasName("pk_credit_packs");

                    b.ToTable("credit_packs", (string)null);
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_transactions");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_credit_transactions_user_id_created_at");

                    b.ToTable("credit_transactions", (string)null);
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.GenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditsCharged")
                        .HasColumnType("integer")
                        .HasColumnName("credits_charged");

                    b.Property<int>("CreditsReserved")
                        .HasColumnType("integer")
                        .HasColumnName("credits_reserved");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FalEndpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fal_endpoint");

                    b.Property<JsonDocument>("FalInput")
                        .HasColumnType("jsonb")
                        .HasColumnName("fal_input");

                    b.Property<JsonDocument>("FalOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("fal_output");

                    b.Property<string>("FalRequestId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fal_request_id");

                    b.Property<string>("OutputR2Key")
                        .HasColumnType("text")
                        .HasColumnName("output_r2key");

                    b.Property<string>("OutputUrl")
                        .HasColumnType("text")
                        .HasColumnName("output_url");

                    b.Property<int>("Product")
                        .HasColumnType("integer")
                        .HasColumnName("product");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_generation_jobs");

                    b.HasIndex("FalRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_generation_jobs_fal_request_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_generation_jobs_user_id_created_at");

                    b.ToTable("generation_jobs", (string)null);
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("integer")
                        .HasColumnName("credit_balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_expires_at");

                    b.Property<int>("ReservedCredits")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_credits");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.VoiceClone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FalVoiceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fal_voice_id");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("SampleR2Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sample_r2key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_voice_clones");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_voice_clones_user_id");

                    b.ToTable("voice_clones", (string)null);
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("AiMedia.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_transactions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.GenerationJob", b =>
                {
                    b.HasOne("AiMedia.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_jobs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.VoiceClone", b =>
                {
                    b.HasOne("AiMedia.Domain.Entities.User", "User")
                        .WithMany("VoiceClones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voice_clones_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMedia.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Transactions");

                    b.Navigation("VoiceClones");
                });
#pragma warning restore 612, 618
        }
    }
}
